import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Online Marketplace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
          rel="stylesheet"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"
          defer
        ></script>
      </Head>
      <main className="flex min-h-screen flex-col bg-gray-900 px-12 py-2">
        <h1 className="my-4 text-4xl">About Online Marketplace</h1>

        <p>
          Welcome to our online marketplace where you can buy, sell, and trade
          any item you desire. Our platform is designed to make the buying and
          selling of goods and services easy and convenient, regardless of your
          location. Whether you're looking to buy a new phone, sell your old
          furniture, or trade in your old clothes, we've got you covered.
        </p>
        <br />
        <p>
          Our marketplace features a wide range of items from all over the
          world, so you can find the perfect item for any occasion. To get
          started, simply create an account on our marketplace and start
          browsing the available items. You can also search for items by
          category, brand, or keyword to find exactly what you're looking for.
          Once you've found the item you want to buy or sell, and we'll take
          care of the rest. We'll also provide you with detailed information
          about the item, including its condition, location, and any available
          options.
        </p>
        <br />
        <p>
          As a seller on our marketplace, you can create an item listing and set
          the price for your item. You can also add photos and descriptions to
          your item to make it more appealing to potential buyers. On our
          marketplace, you can also trade in your old items for new ones, or
          even sell items that you no longer need. We've got you covered with
          our secure online marketplace, so you can sell your items without any
          hassle. Thank you for choosing our online marketplace for all your
          online shopping needs. We hope you find what you're looking for and
          enjoy your online shopping experience.
        </p>
      </main>
    </>
  );
};

export default Home;
